---
title: "summary_code"
author: "Chutiwan Pankram"
date: "2024-11-15"
output: pdf_document
---

```{r}
options(repos = c(CRAN = "https://cran.rstudio.com/"))

install.packages("tidyverse")
install.packages("car")
install.packages("e1071")
install.packages("data.table")
```

```{r}
library(readr)
library(tidyverse)

data <- read_tsv("C:/Users/chuti/OneDrive/Documents/GitHub/Assignment3_6737933/raw_data/PlateletHW.tsv")

data_clean <- data %>%
  mutate(ADP_abs = abs(ADP))

data_clean$ADP_abs <- unlist(data_clean$ADP_abs)
data_clean$ADP <- NULL
names(data_clean)[names(data_clean) == "ADP_abs"] <- "ADP"
data_clean <- data_clean[, c("IID", "ADP", setdiff(names(data_clean), c("IID", "ADP")))]

write_tsv(data_clean, "C:/Users/chuti/OneDrive/Documents/GitHub/Assignment3_6737933/clean_data/PlateletHW_clean.tsv")

```

```{r}
library(car)
scatterplot(Resistance ~ ADP, data=data_clean, reg.line
            = lm, smooth=FALSE)
```

```{r}
library(tidyverse)
library(ggplot2)
library(e1071)
library(data.table)
# Checking clean data histogram
ggplot(data_clean, aes(x =ADP)) + 
  geom_histogram(binwidth = 5, fill = "violetred1", color = "yellow") +
  theme_minimal() +
  labs(title = "Histogram of CLEAN_ADP Levels", x = "ADP Level", y = "Frequency")

```

```{r}
# Check a boxplot graph
ggplot(data_clean,aes(y= ADP)) + geom_boxplot()
```


```{r}
#Check skewness
clean_skewness_value <- skewness(data_clean$ADP) #  right skewness  
# Identify outliers using IQR method  
Q1 <- quantile(data_clean$ADP, 0.25)
Q3 <- quantile(data_clean$ADP, 0.75)
IQR_value <- IQR(data_clean$ADP)
lower_bound <- Q1 - 1.5 * IQR_value
upper_bound <- Q3 + 1.5 * IQR_value
outliers_iqr <- data_clean %>%
  filter(ADP < lower_bound | ADP > upper_bound)   # There is no outliers that less than Q1 - 1.5 * IQR value or more than Q3 + 1.5 * IQR value.

cat("Number of outliers by IQR method:", nrow(outliers_iqr), "\n")  
```

```{r}
data_clean$ADP_log <- log(data_clean$ADP)
```

```{r}
liner_logA <- lm(ADP_log ~ rs4244285, data = data_clean)
liner_logB <- lm(ADP_log ~ rs4986893, data = data_clean)
linear_logC <- lm(ADP_log ~ rs662, data = data_clean)

```

```{r}
library(ggplot2)
summary(liner_logA)

ggplot(data_clean, aes(x = rs4244285, y = ADP_log)) +
  geom_point() +
  geom_smooth(method = "lm", color = "violetred1") +
  labs(title = "Association between log ADP and rs4244285",
       x = "rs4244285 Genotype (0, 1, 2)",
       y = "ADP-Induced Platelet Aggregation") +
  theme_minimal()

```


```{r}
qqnorm(liner_logA$residuals)
qqline(liner_logA$residuals, col = "violetred1")
```

```{r}
library(ggplot2)
summary(liner_logB)


ggplot(data_clean, aes(x = rs4986893 , y = ADP_log)) +
  geom_point() +
  geom_smooth(method = "lm", color = "violetred1") +
  labs(title = "Association between log ADP and rs4986893",
       x = "rs4986893 Genotype (0, 1, 2)",
       y = "ADP-Induced Platelet Aggregation") +
  theme_minimal()
```

```{r}
qqnorm(liner_logB$residuals)
qqline(liner_logB$residuals, col = "violetred1")
```

```{r}
summary(linear_logC)

ggplot(data_clean, aes(x = rs662 , y = ADP_log)) +
  geom_point() +
  geom_smooth(method = "lm", color = "violetred1") + 
  labs(title = "Association between log ADP and rs662",
       x = "rs662 Genotype (0, 1, 2)",
       y = "ADP-Induced Platelet Aggregation") +
  theme_minimal()
```


```{r}
qqnorm(linear_logC$residuals)
qqline(linear_logC$residuals, col = "violetred1")
```

```{r}
snp_list <- c("rs4244285", "rs4986893", "rs662")

results_list <- list()

for (snp in snp_list) {
  model_sum <- lm(as.formula(paste("ADP_log ~ AGE + SEX +", snp)), data = data_clean)
  results_list[[snp]] <- summary(model_sum)
}
print(results_list[["rs4244285"]]) # significant only SNP
print(results_list[["rs4986893"]])# significant only SNP
print(results_list[["rs662"]]) # not siginifcant all variables
```

